version: "3.8"
services:
  mysql:
    container_name: mysql
    image: mysql
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 4171777a737839383720
      MYSQL_DATABASE: blow-db
      MYSQL_USER: CLIENT_USER
      MYSQL_PASSWORD: 6975
      TZ: Europe/Paris
    ports:
      - "9906:3306"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    restart: always
    environment:
      PMA_HOST: mysql
      TZ: Europe/Paris
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:


volumes:
  db:
